name: Content Creator Workflow App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './contentcreator-app/package-lock.json'
      - name: Install dependencies
        working-directory: ./contentcreator-app
        run: npm ci
      - name: Run linting
        working-directory: ./contentcreator-app
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './contentcreator-app/package-lock.json'
      - name: Install dependencies
        working-directory: ./contentcreator-app
        run: npm ci
      - name: Run unit tests
        working-directory: ./contentcreator-app
        run: npm run test:unit
      - name: Run integration tests
        working-directory: ./contentcreator-app
        run: npm run test:integration
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./contentcreator-app/coverage/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './contentcreator-app/package-lock.json'
      - name: Install dependencies
        working-directory: ./contentcreator-app
        run: npm ci
      - name: Build application
        working-directory: ./contentcreator-app
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./contentcreator-app/.next/

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './contentcreator-app/package-lock.json'
      - name: Install dependencies
        working-directory: ./contentcreator-app
        run: npm ci
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./contentcreator-app/.next/
      - name: Install Cypress
        working-directory: ./contentcreator-app
        run: npm install cypress --save-dev
      - name: Run E2E tests
        working-directory: ./contentcreator-app
        run: |
          npm start & npx wait-on http://localhost:3000
          npm run test:e2e
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ./contentcreator-app/cypress/screenshots/
